<!DOCTYPE html>
<html lang="es">
    <head>
        <meta charset="UTF-8">
        <title>MUNDUS ARTIS</title>
        <link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl(); ?>/css/bootstrap.css">        
        <link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl(); ?>/css/bootstrap.responsive.css">         
        <link rel="stylesheet"  type="text/css" href="<?php echo $this->baseUrl(); ?>/css/estilos.css" />
        <link rel="stylesheet"  type="text/css" href="<?php echo $this->baseUrl(); ?>/css/lightbox.css" />
        <script src="<?php echo $this->baseUrl(); ?>/js/modernizr.js" type="text/javascript" charset="utf-8"></script>
        <script src="<?php echo $this->baseUrl(); ?>/js/prefixfree.min.js" type="text/javascript" charset="utf-8"></script>
        <script src="<?php echo $this->baseUrl(); ?>/js/bootstrap.js" type="text/javascript"></script>
        <script src="<?php echo $this->baseUrl(); ?>/js/jquery-1.7.2.min.js" type="text/javascript"> </script>
        <script src="<?php echo $this->baseUrl(); ?>/js/jquery-ui.min.js" type="text/javascript"></script> 
        <script src="<?php echo $this->baseUrl(); ?>/js/main.js"></script>
        <script src="<?php echo $this->baseUrl(); ?>/js/lightbox.js"></script> 
    </head>
    <body>
        
            <section id="formLogin">
                <?php echo $this->layout()->content; ?>
            </section>            
               
    </body>

</html>


