<!DOCTYPE html>
<html lang="es">
    <head>
        <meta charset="UTF-8">
        <title>MUNDUS ARTIS</title>
        <link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl(); ?>/css/bootstrap.css">        
        <link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl(); ?>/css/bootstrap.responsive.css">         
        <link rel="stylesheet"  type="text/css" href="<?php echo $this->baseUrl(); ?>/css/estilos.css" />
        <link rel="stylesheet"  type="text/css" href="<?php echo $this->baseUrl(); ?>/css/lightbox.css" />
        <script src="<?php echo $this->baseUrl(); ?>/js/modernizr.js" type="text/javascript" charset="utf-8"></script>
        <script src="<?php echo $this->baseUrl(); ?>/js/prefixfree.min.js" type="text/javascript" charset="utf-8"></script>
        <script src="<?php echo $this->baseUrl(); ?>/js/bootstrap.js" type="text/javascript"></script>        
        <script src="<?php echo $this->baseUrl(); ?>/js/jquery-1.7.2.min.js" type="text/javascript"> </script>
        <script src="<?php echo $this->baseUrl(); ?>/js/jquery-ui.min.js" type="text/javascript"></script> 
        <script src="<?php echo $this->baseUrl(); ?>/js/bootstrap-modal.js" type="text/javascript"></script>
        <script src="<?php echo $this->baseUrl(); ?>/js/main.js"></script>
        <script src="<?php echo $this->baseUrl(); ?>/js/lightbox.js"></script> 
        <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/js/table/table.js"></script>
        <script src="<?php echo $this->baseUrl(); ?>/js/setup.js" type="text/javascript"></script>
        <script type="text/javascript">

        $(document).ready(function () {
            setupLeftMenu();

            $('.datatable').dataTable();
			setSidebarHeight();


        });
        </script>
    </head>
    <body>
        <div class="container-fluid">
            <header>
                <div class="row-fluid">
                    <div class="span6">
                        <div class="headerLeft">
                            <h1>Ali Luk Moda</h1>
                        </div>
                    </div>
                    <div class="span6">
                        <div class="headerRight">
                            <div class="headerRightText">
                                <ul>
                                    <li>Hola Daniel</li>
                                    <li>|</li>
                                    <li><a href="<?php echo $this->url(array('module'=>'login','controller'=>'logout','action'=>'index')) ?>">Cerrar Sesión</a></li>
                                </ul>
                            </div>                            
                        </div>
                    </div>
                </div>
            </header>
            <nav>
                <ul>
                    <li class="liTelas"><a href="<?php echo $this->url(array('module'=>'default','controller'=>'telas','action'=>'index')); ?>">Telas</a></li>
                    <li class="liPrendas"><a href="<?php echo $this->url(array('module'=>'default','controller'=>'prendas','action'=>'index')); ?>">Prendas</a></li>
                    <li class="liCotizar"><a href="<?php echo $this->url(array('module'=>'default','controller'=>'cotizacion','action'=>'index')); ?>">Cotizar</a></li>
                    <li class="liClientes"><a href="<?php echo $this->url(array('module'=>'default','controller'=>'clientes','action'=>'index')); ?>">Clientes</a></li>
                    <li class="liControles"><a href="<?php echo $this->url(array('module'=>'default','controller'=>'controles','action'=>'index')); ?>">Controles</a></li>
                    <li class="liUsuarios" ><a href="<?php echo $this->url(array('module'=>'default','controller'=>'usuarios','action'=>'index')); ?>">Usuarios</a></li>
                </ul>
            </nav>            
        </div>
        <div class="container-fluid">
            <div class="row-fluid">
                <div class="span2">
                    <div class="siderbarLeft">
                        s
                    </div>
                </div>
                <div class="span10">
                    <div class="siderbarCenter">
                         <?php echo $this->layout()->content; ?>
                    </div>                    
                </div>
            </div>
        </div>
           
                
                  
               
    </body>

</html>



