<table class="tableNuevo" align="center">
    <tr>
        <td class="tdTableNuevo">Ruc</td>
        <?php echo $this->element->getElement('cl_ruc'); ?>
    </tr>
    <tr>
        <td class="tdTableNuevo">Razon social</td>
        <?php echo $this->element->getElement('cl_razon_social'); ?>
    </tr>
    <tr>
        <td class="tdTableNuevo">Dirección</td>
        <?php echo $this->element->getElement('cl_direccion'); ?>
    </tr>
    <tr>
        <td class="tdTableNuevo">Teléfono</td>
        <?php echo $this->element->getElement('cl_telefono'); ?>
    </tr>
    <tr>
        <td class="tdTableNuevo">Contacto</td>
        <?php echo $this->element->getElement('cl_contacto'); ?>
    </tr>
    <tr>
        <td class="tdTableNuevo">Email</td>
        <?php echo $this->element->getElement('cl_email'); ?>
    </tr>
    <tr>
        <?php echo $this->element->getElement('guardar'); ?>
    </tr>
</table>