<table class="tableNuevo" align="center">
    <tr>
        <td class="tdTableNuevo">Nombre</td>
        <?php echo $this->element->getElement('pr_nombre'); ?>
    </tr>
    <tr>
        <td class="tdTableNuevo">Metraje</td>
        <?php echo $this->element->getElement('pr_metraje'); ?>
    </tr>
    <tr>
        <td class="tdTableNuevo">Foto</td>
        <td><?php echo $this->element->getElement('pr_foto'); ?></td>
    </tr>
    <tr>
        <?php echo $this->element->getElement('guardar'); ?>
    </tr>
</table>