
<table class="tableNuevo" align="center">
    <tr>
        <td class="tdTableNuevo">Nombre</td>
        <?php echo $this->element->getElement('te_nombre'); ?>
    </tr>
    <tr>
        <td class="tdTableNuevo">Precio</td>
        <?php echo $this->element->getElement('te_precio'); ?>
    </tr>
    <tr>
        <td class="tdTableNuevo">Descripción</td>
        <?php echo $this->element->getElement('te_descripcion'); ?>
    </tr>
    <tr>
        <?php echo $this->element->getElement('guardar'); ?>
    </tr>
</table>

