<div class="verGeneral">
    <div class="row-fluid" align="center">
        <h1><?php echo $this->title; ?></h1>
    </div>
    <div class="row-fluid">
        <div class="span6">
            <div class="imgVer">
                <img src="<?php echo $this->baseUrl().'/images/prendas/'.$this->foto; ?>"  height="20%"></img>
            </div>            
        </div>
        <div class="span6">
            <p>Color: Negro</p>
        </div>
        
        
    </div>
</div>

<?php //if(count($this->row)){ 
     //foreach ($this->row as $row): ?>
         
 <?php   // endforeach;
    ?>

<?php //} ?>